# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-06-12 03:17
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0002_auto_20180607_1421'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='bookinfo',
            managers=[
                ('books1', django.db.models.manager.Manager()),
            ],
        ),
    ]
